
package view;

import javax.swing.JOptionPane;
import model.DuLieu;
public class MenuForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuForm.class.getName());

    /**
     * Creates new form MenuForm
     */
    public MenuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDangtin = new javax.swing.JButton();
        btnDanhSach = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnThongTin = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnQuanLyTaiKhoan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU Chính");

        btnDangtin.setText("Đăng tin");
        btnDangtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangtinActionPerformed(evt);
            }
        });

        btnDanhSach.setText("Danh sách bài đăng");
        btnDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");

        btnThongTin.setText("Thông tin cá nhân");

        btnDangXuat.setText("Đăng Xuất");

        jButton1.setText("Quản lý bài đăng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnQuanLyTaiKhoan.setText("Quản lý tài khoản");
        btnQuanLyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDangtin)
                            .addComponent(jButton1)
                            .addComponent(btnDanhSach)
                            .addComponent(btnTimKiem)
                            .addComponent(btnThongTin)
                            .addComponent(btnDangXuat)
                            .addComponent(btnQuanLyTaiKhoan))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDangtin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDanhSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThongTin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDangXuat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuanLyTaiKhoan)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangtinActionPerformed
        
    DangTinForm form = new DangTinForm();
    form.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnDangtinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
QuanLyBaiDangForm form = new QuanLyBaiDangForm();
form.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachActionPerformed
DanhSachBaiDangForm form = new DanhSachBaiDangForm();
form.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnDanhSachActionPerformed

    private void btnQuanLyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyTaiKhoanActionPerformed
        QuanLyTaiKhoanForm qltk = new QuanLyTaiKhoanForm();
        qltk.setVisible(true);// TODO add your handling code here:
        qltk.setLocationRelativeTo(null);
        new view.QuanLyTaiKhoanForm().setVisible(true);
    }//GEN-LAST:event_btnQuanLyTaiKhoanActionPerformed
    private boolean kiemTraTaiKhoanBiKhoa() {
    // Nếu tài khoản hiện tại đang đăng nhập bị Admin đánh dấu là bị khóa
    if (DuLieu.nguoiDungDangNhap != null && model.DuLieu.laTaiKhoanBiKhoa(DuLieu.nguoiDungDangNhap.getMaSV())) {
        JOptionPane.showMessageDialog(this, 
                "Tài khoản của bạn đã bị khóa bởi Admin! Hệ thống sẽ tự động đăng xuất.", 
                "Thông báo lỗi", 
                JOptionPane.ERROR_MESSAGE);
        
        // Reset phiên đăng nhập và đẩy về màn hình đăng nhập
        DuLieu.nguoiDungDangNhap = null;
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose(); // Đóng MenuForm lại
        
        return true; // Xác nhận tài khoản ĐÃ bị khóa
    }
    return false; // Tài khoản vẫn hoạt động bình thường
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDangtin;
    private javax.swing.JButton btnDanhSach;
    private javax.swing.JButton btnQuanLyTaiKhoan;
    private javax.swing.JButton btnThongTin;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
